### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by djc** [ctz/rustls#541]
rustls uses uppercase acronyms in type names, contra the API guidelines:

> In `UpperCamelCase`, acronyms and contractions of compound words count as one word: use `Uuid` rather than `UUID`, `Usize` rather than `USize` or `Stdin` rather than `StdIn`.

IMO it would be nice to align with the broader ecosystem here, particularly in something as visible as `TLSError`. On the other hand, changing it might not be worth the pain across the ecosystem. Even in that case, it might be good to change private names and/or stick to the API guidelines for new additions (such as the ECH stuff in #539.

**Comment by sayrer** [comment]
Agreed. I tried to blend in with the rest of handshake.rs, but I didn't really know what to do.

**Comment by ctz** [comment]
Maybe a better name for this type is just `rustls::Error`?

**Comment by briansmith** [comment]
> Maybe a better name for this type is just `rustls::Error`?

SGTM.

Note you can also do `#[deprecated] pub type TLSError = Error;` to ease the transition, although I'd be fine if that was skipped.

**Comment by djc** [comment]
> Maybe a better name for this type is just `rustls::Error`?

👍 So rename the error type and adjust other types to align with the guidelines? Feel like having a deprecated alias for one cycle?

**Comment by ctz** [comment]
It seems pretty low cost to have the deprecated alias, so let's do that IMO.

**Comment by djc** [comment]
What about enum variant names, including those for all those IANA constants? `CHACHA20_POLY1305` => `Chacha20Poly1305`? (I can focus on doing the public API types first, and leave the `internal` module alone.) Should we rename `ciphersuite` to `cipher_suite` everywhere?

**Comment by ctz** [comment]
I think things which are named after external standards should use the naming in those standards, as far as possible. I think that means:

- `CHACHA20_POLY1305_SHA256` as a cipher suite name (but we should fix `BulkAlgorithm` item names)
- `cipher_suite` instead of `ciphersuite`

But, yes, let's concentrate on any public changes first.

**Comment by djc** [comment]
More things to consider:

* Inconsistency like `cert`/`certificate`, `sig`/`signature` in names
* The trait name style of `ProducesTickets`, `ResolvesServerCert` seems fairly unidiomatic as well, I think either `TicketProducer` or `ProduceTicket` would be more common style (I think I prefer the former)

**Comment by briansmith** [comment]
`AEADTicketer` -> `AeadTicketer`.

**Comment by djc** [comment]
> `AEADTicketer` -> `AeadTicketer`.

See #619.

**Comment by briansmith** [comment]
There are other cases where this wasn't done. `WebPKIVerifier` is the one I remember off the top of my head.

**Comment by cpu** [comment]
> There are other cases where this wasn't done. WebPKIVerifier is the one I remember off the top of my head.

This looks resolved in `main`: we have `WebPkiClientVerifier` and `WebPkiServerVerifier`.

Short of other specific examples to fix, can we consider this done?

**Comment by briansmith** [comment]
> Short of other specific examples to fix, can we consider this done?

I would close it if the clippy lints for this are being enforced in CI, and if somebody has done a search through the codebase (probably for just two adjacent capital letters) to make sure the lints didn't overlook anything.

**Comment by djc** [comment]
IIRC we still have a bunch of code exposed via the `internals` namespace that doesn't follow the convention, but in terms of public/stable API I think we're in a good place here.

**Comment by cpu** [comment]
I've done a pass in https://github.com/rustls/rustls/pull/1543 that I think caught the remaining instances.

> I would close it if the clippy lints for this are being enforced in CI

@briansmith I've added [`upper_case_acronyms`](https://rust-lang.github.io/rust-clippy/rust-1.72.0/index.html#/upper_case_acronyms). Were there any other lints you had in mind?

> if somebody has done a search through the codebase (probably for just two adjacent capital letters) to make sure the lints didn't overlook anything.

I used this approach to try and find remaining instances for #1543.

> IIRC we still have a bunch of code exposed via the internals namespace that doesn't follow the convention

It seemed like the majority were in `rustls/src/msgs/handshake.rs` :thinking:
