### ISSUE TITLE
Allow disabling Hostname Verification

### ISSUE THREAD

**Issue by roblabla** [ctz/rustls#578]
Hello,

I'm working on an application that uses `rustls` to secure its client/server communications. We have our own private Root CA we use to make sure our communications are secure. In our threat model, the hostname validation isn't particularly useful: If the remote server has a valid certificate, it doesn't really matter through which domain name we connected to it, we know the connection is legitimate. Furthermore, it's causing us a fair amount of pain: The certificates being bound to a particular domain name means moving services to new domain names requires reprovisioning a certificate.

We could implement this ourselves by providing a custom `ServerCertVerifier` that simply doesn't run the last step [here](https://github.com/ctz/rustls/blob/eacc251a27164d86071e74cfb3f45d8d7f940fff/rustls/src/verify.rs#L314). But copy pasting rustls' verifier seems to be fairly dangerous. Ideally, it'd be nice if `rustls` provided a `DangerousClientConfig::disable_hostname_verification` function that would gate the call to `cert.verify_is_valid_for_dns_name`.

**Comment by djc** [comment]
I don't think rustls should be in the business of facilitating different kinds of dangerous configuration. If you want to do something dangerous, then the risk of implementing a custom `ServerCertVerifier` is on you, which seems reasonable to me.

Why do you think copy pasting rustls's verifier is fairly dangerous?

**Comment by sayrer** [comment]
Could you make yourself a wildcard cert for a `.corp` domain? That seems like a better approach than changing rustls.

**Comment by ctz** [comment]
I don't think we're going to do this, and the supported way to achieve this is to supply your own `ServerCertVerifier`.

**Comment by lambdalisue** [comment]
I faced same request and solved with the following code. In case you are interested in.

```rust
struct NoCertVerifier {}

impl rustls::ServerCertVerifier for NoCertVerifier {
    fn verify_server_cert(
        &self,
        _: &rustls::RootCertStore,
        _: &[rustls::Certificate],
        _: webpki::DNSNameRef<'_>,
        _: &[u8],
    ) -> Result<rustls::ServerCertVerified, rustls::TLSError> {
        Ok(rustls::ServerCertVerified::assertion())
    }
}

// ...

let mut config = ClientConfig::new();
config.dangerous().set_certificate_verifier(Arc::new(NoCertVerifier {}));
```

Note that I needed to add `webpki` crate to access `DNSNameRef` as well. I wonder if `rustls` re-export that for user who don't need to access that directly.

**Comment by roblabla** [comment]
@lambdalisue this does not disable hostname verification, it disables *all verifications* and is unlikely to be secure on its own. If you only want to disable hostname verification, here's the proper code (warning, untested, mostly copy pasted from rustls itself):

```rust
fn prepare<'a, 'b>(
    roots: &'b RootCertStore,
    presented_certs: &'a [Certificate],
) -> Result<CertChainAndRoots<'a, 'b>, TLSError> {
    if presented_certs.is_empty() {
        return Err(TLSError::NoCertificatesPresented);
    }

    // EE cert must appear first.
    let cert = webpki::EndEntityCert::from(&presented_certs[0].0).map_err(TLSError::WebPKIError)?;

    let chain: Vec<&'a [u8]> = presented_certs
        .iter()
        .skip(1)
        .map(|cert| cert.0.as_ref())
        .collect();

    let trustroots: Vec<webpki::TrustAnchor> = roots
        .roots
        .iter()
        .map(OwnedTrustAnchor::to_trust_anchor)
        .collect();

    Ok((cert, chain, trustroots))
}
impl ServerCertVerifier for HarfanglabCertVerifier {
    /// Will verify the certificate is valid in the following ways:
    /// - Signed by a valid root
    /// - Not Expired
    fn verify_server_cert(
        &self,
        roots: &RootCertStore,
        intermediates: &[Certificate],
        _dns_name: webpki::DNSNameRef,
        ocsp_response: &[u8],
    ) -> Result<ServerCertVerified, TLSError> {
        // Get the end-entity cert, tthe chain, and the trust root. Error out if
        // chain is empty.
        let (cert, chain, trustroots) = prepare(roots, intermediates)?;

        // Validate the certificate is valid, signed by a trusted root, and not
        // expired.
        let now = SystemTime::now();
        let webpki_now =
            webpki::Time::try_from(now).map_err(|_| TLSError::FailedToGetCurrentTime)?;

        let _cert = cert
            .verify_is_valid_tls_server_cert(
                SUPPORTED_SIG_ALGS,
                &webpki::TLSServerTrustAnchors(&trustroots),
                &chain,
                webpki_now,
            )
            .map_err(TLSError::WebPKIError)
            .map(|_| cert)?;

        if !ocsp_response.is_empty() {
            //trace!("Unvalidated OCSP response: {:?}", ocsp_response.to_vec());
        }

        Ok(ServerCertVerified::assertion())
    }
}
```

Note that the above code is valid for Rustls 0.19. When new versions of rustls come out with improved support for various security features (such as OSCP verifications, or CT Logs), it will always need to be revised to match whatever rustls does in its own ServerCertVerifier [here](https://github.com/ctz/rustls/blob/v/0.19.0/rustls/src/verify.rs#L253).

This is what I meant when I said copy pasting rustls code is dangerous: It is likely to expand in the future as more features are integrated into it, and as the WebPKI security model evolves. This means constant maintenance is required to disable only a single check.

**Comment by lambdalisue** [comment]
@roblabla 

Thanks a lot. I could not find this kind of sample codes in rustls docs, repos, or whatever so I ended up with disabling all verifications at that time 😢 
Your code seems more specific for the situation, thanks 👍

**Comment by iptq** [comment]
@djc

> I don't think rustls should be in the business of facilitating different kinds of dangerous configuration. If you want to do something dangerous, then the risk and effort of implementing and maintaining a custom ServerCertVerifier is on you, which seems reasonable to me.

To me, it seems like disabling just the hostname verification part seems like a fairly common use-case. Since there's already a feature gate for `dangerous_configuration`, I think it would be useful to implement the option for selectively disabling checks, and then gating the configuration methods behind the feature gate. Otherwise, people who want the feature will inevitably "copy pasting rustls's verifier" in order to achieve this feature, which as you pointed out is more dangerous for the ecosystem altogether.

Please reconsider revisiting #146, or if it's too old then reapplying the patch to latest.

**Comment by djc** [comment]
@iptq judging from the traffic this issue has received, I would dispute your qualification of "fairly common". I think we want to facilitate either (a) safe configuration or (b) hooks that let you configure your own verification, but that doesn't mean we want to take on the maintenance burden of all the nuances of how people might want to skip some part of verification.

> Otherwise, people who want the feature will inevitably "copy pasting rustls's verifier" in order to achieve this feature, which as you pointed out is more dangerous for the ecosystem altogether.

The difference here is that those people need to take responsibility for their verifier implementation, rather than us taking on responsibility for a bunch of different insecure verification mechanisms and those mechanisms doing exactly what downstream users expect.

**Comment by iptq** [comment]
There's a slew of other issues that are basically asking the same question, this just happens to be the most recent:
- #64
  - looks like this actually got implemented in #70 which included a no-op verifier, but that's not necessarily what people want, which is just disabling the hostname checking but still performing the rest of the steps.
- #123 
- https://github.com/rustls/rustls/issues/124#issuecomment-337994671 this particular comment
- #144
- #146 as I mentioned above

There's some other possibly related ones but they seem to have different root problems so I left them out.

The thing here is each of the checks currently in `WebPkiVerifier` (valid authority, expiry, matches the DNS host, actual certificate status) are completely independent of each other, so gating each step behind a config flag should effectively only disable that one check, and not affect the others. If those config flags are gated behind `dangerous_configuration` it would still protect the integrity of the library for users of the standard flags and those who choose to turn on the dangerous feature are at their own risk, albeit less dangerous than if they were to roll custom verifiers.

Another option would be to encapsulate each check into a function only exposed to people who are using the dangerous feature, which would help in safety of their custom configurations. The difference here is now people can still rely on the expertise of the maintainers of upstream to get the logic of each check correctly.

It seems like the advice from the other issues is resulting in people running around with their own forks and haphazardly copy/paste custom verifiers when all they really wanted was one part of the check to be optional. For such a critical library as rustls, this seems a lot less secure.

Really hope you reconsider but if the answer's still no I'll probably go the copy/paste route as well.

**Comment by quininer** [comment]
I think we can have an independent crates to place these incomplete verifiers, it does not have to be owned by rustls.

**Comment by djc** [comment]
I'll just quote https://github.com/rustls/rustls/pull/146#issuecomment-354601275 here, as well:

> I'm afraid this is still problematic for me. The ultimate aim of all the certificate checking is to see that one of the root certificates signed a certificate for example.com. Without the hostname check, all the of the other remaining checks don't achieve much. The supported way to remove all these checks is to provide a `rustls::verify::ServerCertVerifier` which does nothing. At which point, you may consider some kind of trust-on-first-use style pinning of the whole certificate chain for these devices.
> 
> I know that implementing a do-nothing ServerCertVerifier is kind of annoying, but in this project I'm trying to make it easy to do common things, and not-easy to do uncommon/unsafe things. So I think the cost of ~10 lines of code in every project that wants to do something uncommon is OK.

In particular:

**Without the hostname check, all the of the other remaining checks don't achieve much.**

So yes, there could be an independent crate for this, but we may still not want to facilitate this. Also note that some of those issues predated the support for generic verification support in rustls, and some of them have fairly straightforward workarounds that would yield more secure deployments.

Also, it would be more useful if folks who want this explained why they want this -- let's talk about the problems rather than a potential solution.

**Comment by adeschamps** [comment]
We're in a similar situation, where we don't want to verify the hostname, but would like to keep the other checks. With Rustls 0.19, we copy-pasted the implementation much like @roblabla shows. However, in Rustls 0.20, `OwnedTrustAnchor::to_trust_anchor` is now private, and I haven't found a way to provide the right arguments to `verify_is_valid_tls_server_cert` without it. Can you suggest a path forward?

**Comment by djc** [comment]
The 0.20 API is quite different and, in this case, shouldn't require the use of the `rustls::RootCertStore`. As such, you can just pass `webpki::TrustAnchor`s directly from webpki-roots or some other collection to `webpki::EndEntityCert::verify_is_valid_tls_server_cert()`.

However, I would again strongly suggest that, if you're unable to navigate the documentation to figure this out, it seems really dangerous to be disabling parts of the TLS protocol verification.

**Comment by adeschamps** [comment]
> The 0.20 API is quite different and, in this case, shouldn't require the use of the `rustls::RootCertStore`.

I've now recognized that this is true -- although the provided `impl ServerCertVerifier for WebPkiVerifier` _does_ use `RootCertStore` -- it's just using an API that is now private, which puts users in a position where they can't as easily use the provided implementation as starting point.for their own implementation.

I managed to accomplish my goals with some small refactors of our own code -- we were previously passing around just a `RootCertStore`; I made sure that the `Certificate`s from which it was constructed are still available to our `ServerCertVerifier` implementation, so that I can construct the `webpki::TrustAnchor`s to pass to `verify_is_valid_tls_server_cert`.

**Comment by nyurik** [comment]
I also feel it would be highly beneficial to the community to provide this, simply because it helps all those migrating from openssl.  For example, in openssl my old code did this:

```rust
connector.set_callback(|cfg, _domain| {
    cfg.set_verify_hostname(false);
    Ok(())
});
```

The suggestion to "do it differently" is often irrelevant, because of the legacy systems that are used everywhere and cannot be changed by millions of their users.  A good example is connecting to PostgreSQL with [ssl support](https://www.postgresql.org/docs/15/libpq-ssl.html), which has 3+ SSL modes:
* `sslmode=required` / `preferred` -- this is the *default*, and used by the vast majority of the connections - connect to server using SSL encryption, but do **NOT** verify anything -- i.e. postgres uses snakeoil certs.  (Eavesdropping protection, but no man-in-the-middle protection)
* `sslmode=verify-ca` -- cert verification, but no host verification
* `sslmode=verify-full` -- cert and hostname verification

So any code out there that gives users a way to connect to postgres must write tons of code to support all those cases already, and rustls makes this even more difficult.

**Comment by djc** [comment]
I suggest you propose an API for this as PR. I think it should be some kind of builder API exposed through the `dangerous_config()` getter.

**Comment by nyurik** [comment]
@djc et al, I have implemented the rough draft API https://github.com/rustls/rustls/pull/1197 to show how we can add dangerous verifiers that have well understood and documented risk factors, rather than let each user shoot themselves in the foot in the most creative way.  Plus this helps with the OpenSSL -> Rustls migrations.

**Comment by doroved** [comment]
Who has a working example with the current version of rustls? How to disable hostname validation? I killed the whole day, but I still can't do it! In native_tls it is simply done via **danger_accept_invalid_hostnames**.

**Comment by nyurik** [comment]
yeah, it is a bit of a hoop every dev still has to jump through. My code that establishes the non-host-validated (per PostgreSQL requirement) connection is in https://github.com/maplibre/martin/blob/main/martin/src/pg/tls.rs

**Comment by doroved** [comment]
> yeah, it is a bit of a hoop every dev still has to jump through. My code that establishes the non-host-validated (per PostgreSQL requirement) connection is in https://github.com/maplibre/martin/blob/main/martin/src/pg/tls.rs

You have the entire certificate validation ignored, and only need to ignore the server name.
I Need to ignore this error:
**InvalidCertificate(NotValidForName)**

**Comment by doroved** [comment]
> yeah, it is a bit of a hoop every dev still has to jump through. My code that establishes the non-host-validated (per PostgreSQL requirement) connection is in https://github.com/maplibre/martin/blob/main/martin/src/pg/tls.rs

Here's a working example I created with people from the Rust community, use it if you've been looking for a similar solution for a while.
https://gist.github.com/doroved/2c92ddd5e33f257f901c763b728d1b61
